name: vehicle_sharing_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3

  # Firebase
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6
  firebase_core: ^1.0.4
  firebase_storage: ^8.0.4
  firebase_database: ^6.1.2

  # Google Maps
  google_maps_flutter: ^2.0.3
  geolocator: ^7.0.3
  flutter_polyline_points: ^1.0.0
  flutter_geofire: ^2.0.0

  image_cropper: ^1.3.1
  cached_network_image: ^2.4.1
  connectivity: ^3.0.2
  http: ^0.13.1
  razorpay_flutter: ^1.2.5
  toast: ^0.1.5
  table_calendar: ^3.0.0
  image_picker: ^0.7.4
  auto_size_text: ^3.0.0-nullsafety.0
  introduction_screen: ^3.0.2
  shared_preferences: ^2.0.6
  qr_code_scanner: ^0.5.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.0
  flutter_app_name: ^0.1.1

flutter:

  uses-material-design: true
  assets:
     - images/
     - images/onboarding/

  fonts:
     - family: MuseoModerno
       fonts:
         - asset: fonts/MuseoModerno-ExtraLight.ttf
     - family: OpenSans
       fonts:
          - asset: fonts/OpenSans-Regular.ttf
     - family: Inter
       fonts:
          - asset: fonts/Inter-Light.ttf
     - family: Segoe
       fonts:
         - asset: fonts/segoepr.ttf

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: images/splashscreen.png
  android: true
  ios: true
  fullscreen: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher.png"


# flutter pub run flutter_app_name
flutter_app_name:
  name: "Bikester"